apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 975050362429.dkr.ecr.us-east-1.amazonaws.com/firebase-java/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080