name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: tzejunw/cs203.git@v0.1.0
      with:
        # Such as https://github.com/tzejunw/git-repo-sync.git
        target-url: https://github.com/tzejunw/cs203.git
        # Such as wangchucheng
        target-username: tzejunw
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.TOKEN_203 }}
